[package]
name = "replace"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ignore = "*"
num_cpus = "*"
deque = "*"
regex = "*"
clap = "*"
crossbeam-utils = "0.8"
anyhow = "*"